-- local latte = require("catppuccin.palettes").get_palette("latte")
-- local frappe = require("catppuccin.palettes").get_palette("frappe")
-- local macchiato = require("catppuccin.palettes").get_palette("macchiato")
-- local mocha = require("catppuccin.palettes").get_palette("mocha")
--
-- require("catppuccin").setup({
--   color_overrides = {
--     macchiato = {
--       base = "#000000",
--       mantle = "#000000",
--       crust = "#000000",
--     },
--   },
--   float = { solid = true, transparent = false },
-- })
